# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=30)),
                ('d_color', models.CharField(max_length=10)),
                ('d_age', models.IntegerField()),
                ('isdelet', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dog',
                'ordering': ['d_age'],
            },
            managers=[
                ('myobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
